### ISSUE TITLE
leaderboard.js bruh

### ISSUE THREAD

**Issue by TheNoob27** [outlaylol/economybot#8]
leaderboard.js not working no matter whatever i try, so i’m wondering if it still works for you..?

there have been issues before this but the answers weren’t really defined or it just didn’t work >~>

**Comment by xenowing** [comment]
For latest versions```js
let money = db.all().filter(data => data.ID.startsWith(`money`)).sort((a, b) => b.data - a.data)
    money.length = 10;
    var finalLb = "";
    var i = 0;
    let indexnum = 0;
    for (i in money) {
      finalLb += `**${++indexnum}. <@${client.users.get(money[i].ID.split('_')[1]).id}>** - ${money[i].data} :dollar:\n`;
    }

    
    const embed = new Discord.RichEmbed()
    .setAuthor(`Leaderboard!`, message.guild.iconURL)
    .setColor(message.member.displayHexColor)
    .setDescription(finalLb)
    .setFooter(client.user.tag, client.user.displayAvatarURL)
    .setTimestamp()
    message.channel.send(embed)```

**Comment by TheNoob27** [comment]
i actually don’t need this anymore, but thanks, it’s helpful

**Comment by TheNoob27** [comment]
i forgot to close this, when i finally figured it out lol
